[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jobs-scraper"
version = "0.1.0"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.in"] }

[project.scripts]
jobs-scraper = "jobs_scraper.__main__:main"
